### ISSUE TITLE
linux培训可以加些实用命令的使用

### ISSUE THREAD

**Issue by wangqr** [eesast/Training#11]
`htop`、`tmux`之类，或者啥时候我去统计下bash history，还可以介绍WSL

**Comment by WangMinhu** [comment]
非常赞成

**Comment by wangqr** [comment]
[统计了一下](https://gist.github.com/wangqr/36d5faf3991dc036a3f61f5904ca0960)

**Comment by wangqr** [comment]
ssh public key & github

**Comment by wangqr** [comment]
考虑下要不要讲docker，以及一个OJ系统的正确架构？
